### ISSUE TITLE
strings_NOT logic incorrect?

### ISSUE THREAD

**Issue by SteveTownsend** [powerof3/Spell-Perk-Item-Distributor#2]
The logic for negation of keywords (etc) looks suspect to me, see _strings_NOT_ in https://github.com/powerof3/Spell-Perk-Item-Distributor/blob/master/SPID/src/Distributor.h - I don't see how this can be the same as _strings_MATCH_ just below and work correctly.

**Comment by powerof3** [comment]
It's not the same, though. Look at the last `result`  comparison.

![image](https://user-images.githubusercontent.com/32599957/148147316-1ca175df-42af-4c9d-82ef-edab99195350.png)

![image](https://user-images.githubusercontent.com/32599957/148147359-b00010a4-173f-4fe7-aa63-78fc5b2e5206.png)

**Comment by SteveTownsend** [comment]
Ah sorry. Trying to work out why Ordinator for NPCs is not working, I
thought this was it. Thanks for getting back to me.
