### ISSUE TITLE
On Death Distribution Spells are not applied

### ISSUE THREAD

**Issue by adya** [powerof3/Spell-Perk-Item-Distributor#60]
When distributing spells on death for some reason, spells/abilities are not applied (works fine with regular distribution)

**Comment by adya** [comment]
True, ability is added to the spell list, but not actually evaluated. Need to RE

**Comment by adya** [comment]
`AddSpell` on actor fixes the problem.

**Comment by adya** [comment]
Fixed in #64

**Comment by powerof3** [comment]
This can also be fixed by adding the spell to the npc spell list and then calling `CastPermanentMagic`.

See https://github.com/powerof3/po3-Tweaks/blob/f971120870bd1afa42ede629781032bf26433022/src/Fixes/ReapplySpellsOnLoad.cpp#L19

**Comment by arkadiihlushchevskyi** [comment]
Funny thing 😄 I've just did exactly that and came back to this issue to leave a comment about it, I guess GitHub does not notify about comments on closed issues, or I missed it 🙈
